export enum RegionEnum{
  blagoevgrad = 1,
burgas = 2,
varna = 3,
velikoTarnovo = 4,
vidin = 5,
vraca = 6,
gabrovo = 7,
dobrich = 8,
dupnica = 9,
kardzhali = 10,
kyustendil = 11,
lovech = 12, 
montana = 13,
pazardhzik = 14,
pernik = 15,
pleven = 16,
plovdiv = 17,
razgrad = 18, 
ruse = 19,
silistra = 20,
sliven = 21,
smolyan = 22,
sofiq = 23,
staraZagora = 24,
tyrgovishte = 25,
haskovo = 26,
shumen = 27,
qmbol = 28,
outOfCountry = 29
}

export const RegionEnumLocalization = {
  [RegionEnum.blagoevgrad]: 'Благоевград',
  [RegionEnum.burgas]: 'Бургас',
  [RegionEnum.varna]:'Варна',
  [RegionEnum.velikoTarnovo]: 'Велико Търново',
  [RegionEnum.vidin]: 'Видин',
  [RegionEnum.vraca]:'Враца',
  [RegionEnum.gabrovo]: 'Габрово',
  [RegionEnum.dobrich]: 'Добрич',
  [RegionEnum.dupnica]:'Дупница',
  [RegionEnum.kardzhali]: 'Кърджали',
  [RegionEnum.kyustendil]: 'Кюстендил',
  [RegionEnum.lovech]:'Ловеч',
  [RegionEnum.montana]: 'Монтана',
  [RegionEnum.pazardhzik]: 'Пазарджик',
  [RegionEnum.pernik]:'Перник',
  [RegionEnum.pleven]: 'Плевен',
  [RegionEnum.plovdiv]: 'Пловдив',
  [RegionEnum.razgrad]:'Разград',
  [RegionEnum.ruse]: 'Русе',
  [RegionEnum.silistra]: 'Силистра',
  [RegionEnum.sliven]:'Сливен',
  [RegionEnum.smolyan]: 'Смолян',
  [RegionEnum.sofiq]: 'София',
  [RegionEnum.staraZagora]:'Стара Загора',
  [RegionEnum.tyrgovishte]: 'Търговище',
  [RegionEnum.haskovo]: 'Хасково',
  [RegionEnum.shumen]:'Шумен',
  [RegionEnum.qmbol]: 'Ямбол',
  [RegionEnum.outOfCountry]:'Извън страната',
  
  
}